### ISSUE TITLE
multicursor substitution example in tutorial not working?

### ISSUE THREAD

**Issue by moesasji** [jyp/boon#104]
Looking through the tutorial I am unable to get the [multicursor example](https://github.com/jyp/boon/blob/master/boon-tutorial.el#L630) to replace all occurrences of a symbol despite multicursor getting installed.

Although all occurrences of the word indeed get selected and removed I only seem to be able to replace the first occurrence with the word command instead of all. The following screenshot is an example to illustrate what happens.

![mc-boon-only-first](https://user-images.githubusercontent.com/1714738/106204731-5a7c4300-61b5-11eb-9cbf-0461e1ceb172.png)

Am I misunderstanding how this is supposed to work or is this functionality broken?

btw) This is on Emacs 27.1; boon @ commit 3dd9669 (none of recent commits seem relevant for this)

**Comment by jyp** [comment]
This was unfortunately broken by an emacs update, and I have not gotten to fix it yet. Thanks for the report!

**Comment by moesasji** [comment]
> This was unfortunately broken by an emacs update, and I have not gotten to fix it yet. Thanks for the report!

In trying to figure out what goes wrong that in part this is a problem between chair and screen. Essentially the answer to [this question](https://stackoverflow.com/questions/58058182/multiple-cursors-in-emacs-does-not-modify-all-the-cursors) on stackoverflow showed me that the problem is that I had hit "no" the first time I used multicursor on this command without realizing. 

If I delete the previously generated [mc-list.el](https://github.com/magnars/multiple-cursors.el/blob/master/multiple-cursors-core.el#L639) based on my previous responses, restart emacs, run the boon-tutorial and then take care to say yes on both insert and delete on the tutorial commands it works as expected. However getting it wrong for the delete operation is surprisingly easy even when knowing this problem exists!

Bottomline: the problem is in whatever ends up in the mc-list.el defaults file. Hopefully that gives an idea how to best fix this.

**Comment by YassinRian** [comment]
if I had read this first I would have saved some hours troubleshooting :)))

**Comment by jyp** [comment]
I do believe that this was fixed some time ago, in fact. Closing for now; feel free to reopen with a specific example.
