### ISSUE TITLE
Search changes result in broken flow

### ISSUE THREAD

**Issue by subsetpark** [jyp/boon#107]
In colemak mode, I used to have this experience:

- input: `f<space>foo<enter>`
- effect: all instances of `foo` are highlighted
- input: `F`
- point moves to next instance of `foo`

I now have this experience:

- input: `f<space>foo<enter>`
- minibuffer prompt: `Highlight using face`
- input: `<enter>`
- effect: all instances of `foo` are highlighted
- input: `F`
- error message: 

```
if: Wrong type argument: stringp, #[257 "#*" [("foo") nil nil search-spaces-regexp case-fold-search re-search-forward t] 5 "

(fn LIMIT)"]
```

Do I need to change how I use search, or is it currently broken?

**Comment by jyp** [comment]
If you don't want hi-lock to ask about the face: `(setq hi-lock-auto-select-face t)` . For the rest, can you test if the error persists with the current version?

**Comment by subsetpark** [comment]
@jyp same issue I'm afraid :(

**Comment by veronikazaglotova** [comment]
Had the same issue
https://github.com/abo-abo/swiper/issues/2810
What's happening?

**Comment by jyp** [comment]
@subsetpark Which exact version of emacs and boon are you using? Are you using swiper or isearch? If swiper, which version?

@veronikazaglotova You don't seem to have the same issue. Do this: (setq hi-lock-auto-select-face t)

**Comment by veronikazaglotova** [comment]
Ok this solves the issue, however the thingies stay highlighted which I don't want honestly.

**Comment by jyp** [comment]
The rationale is that this way you can navigate them thingies. Use boon-quit (escape) to remove the highlight. I very often want this feature: it's there to stay.

**Comment by subsetpark** [comment]
@jyp versions:

boon: `boon-20210215.744`

emacs: `GNU Emacs 28.0.50` (from Archlinux AUR; package manager output below)

```
Name            : emacs-gcc-wayland-devel-bin
Version         : 28.0.50.146924-1
Description     : GNU Emacs. Development native-comp branch and pgtk branch combined, served as a binary.
Architecture    : x86_64
URL             : http://www.gnu.org/software/emacs/
Licenses        : GPL3
Groups          : None
Provides        : emacs  emacs-seq
Depends On      : alsa-lib  cairo  gnutls  gtk3  libxml2  jansson  libotf  harfbuzz  gpm  libgccjit  webkit2gtk
Optional Deps   : None
Required By     : None
Optional For    : notmuch  translate-shell
Conflicts With  : emacs  emacs26-git  emacs-27-git  emacs-git  emacs-seq
Replaces        : emacs26-git  emacs27-git  emacs-git  emacs-seq
Installed Size  : 161.99 MiB
Packager        : Unknown Packager
Build Date      : Tue 16 Feb 2021 08:58:57 AM EST
Install Date    : Tue 16 Feb 2021 08:59:38 AM EST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

I don't think I have any config specified for swiper or isearch, that said, I use `counsel` which has `swiper-20210202.2312` installed as a dependency.

**Comment by jyp** [comment]
I don't experience the bug you're referring to, but your configuration differs from mine quite a bit: I am using emacs 27 and swiper stable. I wonder if something changed in hi-lock? Can you 'describe-variable' hi-lock-interactive-patterns and show what it says?

A complete stack trace might also give a clue as to what is going on.

**Comment by subsetpark** [comment]
describe variable output:

```
hi-lock-interactive-patterns is a variable defined in ‘hi-lock.el’.
Its value is nil

  Automatically becomes permanently buffer-local when set.

Documentation:
Patterns provided to hi-lock by user.  Should not be changed.

[back]
```

**Comment by subsetpark** [comment]
To eliminate the differences, I also pinned swiper to melpa-stable. Unfortunately, same issue.

**Comment by subsetpark** [comment]
Here's a trace after enabling debugger-on-error:

```
Debugger entered--Lisp error: (wrong-type-argument stringp #f(compiled-function (limit) #<bytecode 0x1ae7195b59041723>))
  boon--re(#f(compiled-function (limit) #<bytecode 0x1ae7195b59041723>) t)
  boon-qsearch(t)
  boon-qsearch-next()
  funcall-interactively(boon-qsearch-next)
  command-execute(boon-qsearch-next)
```

Happy to get any more information if you like.

**Comment by jyp** [comment]
If `hi-lock-interactive-patterns` were nil, then you should get the message "Nothing to search: hi-lock something to search before using boon-qsearch.".  I don't really believe that, but you could make sure it is indeed nil before calling `boon-qsearch-next`. Indeed, `(boon-cur-regexp)` is the argument passed to `boon--re`, and it's from `hi-lock-interactive-patterns`.  But you're getting `#f(compiled-function (limit) #<bytecode 0x1ae7195b59041723>)` .  If you indeed see this 'compiled-function' thing in `hi-lock-interactive-patterns`, it means that the function `rx-to-string` is buggy in your version of emacs. You can test this hypothesis  by evaluating:

```
(rx-to-string '(seq
                (any 114 82)
                (any 101 69)
                (any 103 71))
              t)
```
if you get anything else than `"[Rr][Ee][Gg]"` then it's a bug in your version of emacs.

**Comment by subsetpark** [comment]
@jyp You're right, I hadn't understood that you wanted to describe that variable only after I had searched for something. Here it is after a search.

```
hi-lock-interactive-patterns is a variable defined in ‘hi-lock.el’.
Its value is
((#f(compiled-function
     (limit)
     #<bytecode -0x184d6e853b8fe742>)
    (0 'hi-yellow prepend)))
Local in buffer init.el; global value is nil

  Automatically becomes permanently buffer-local when set.

Documentation:
Patterns provided to hi-lock by user.  Should not be changed.
```

**Comment by subsetpark** [comment]
That said, when I run the sample code you wrote above, I *do* get `"[Rr][Ee][Gg]"`.

**Comment by jyp** [comment]
Alright, some more steps to try to pinpoint the bug ...

can you try the following 
1. (boon-set-user-regexp "abcd") and report the value of if hi-lock-interactive-patterns
2. (boon-set-regexp "efgh") and report the value of if hi-lock-interactive-patterns
3. Try to do an isearch (not swiper) for "ijkl" and report the value of if hi-lock-interactive-patterns

**Comment by subsetpark** [comment]
# boon `f <spc>`

```
hi-lock-interactive-patterns is a variable defined in ‘hi-lock.el’.
Its value is
((#f(compiled-function
     (limit)
     #<bytecode -0x16dd77d78192f2f9>)
    (0 'hi-yellow prepend)))
Local in buffer *scratch*; global value is nil

  Automatically becomes permanently buffer-local when set.

Documentation:
Patterns provided to hi-lock by user.  Should not be changed.
```

# Case 1

```
hi-lock-interactive-patterns is a variable defined in ‘hi-lock.el’.
Its value is
((#f(compiled-function
     (limit)
     #<bytecode -0x16dd77d78192f2f9>)
    (0 'hi-yellow prepend)))
Local in buffer *scratch*; global value is nil

  Automatically becomes permanently buffer-local when set.

Documentation:
Patterns provided to hi-lock by user.  Should not be changed.

[back]
```

# Case 2

```
hi-lock-interactive-patterns is a variable defined in ‘hi-lock.el’.
Its value is shown below.

  Automatically becomes permanently buffer-local when set.

Documentation:
Patterns provided to hi-lock by user.  Should not be changed.

Value:
((#f(compiled-function
     (limit)
     #<bytecode 0xdfbb89d7821003>)
    (0 'hi-pink prepend))
 (#f(compiled-function
     (limit)
     #<bytecode -0x16dd77d78192f2f9>)
    (0 'hi-yellow prepend)))
Local in buffer *scratch*; global value is nil

[back]
```

# Case 3 (after isearch-forward)

```
hi-lock-interactive-patterns is a variable defined in ‘hi-lock.el’.
Its value is shown below.

  Automatically becomes permanently buffer-local when set.

Documentation:
Patterns provided to hi-lock by user.  Should not be changed.

Value:
((#f(compiled-function
     (limit)
     #<bytecode -0x15a3c9a0f192ff5f>)
    (0 'hi-green prepend))
 (#f(compiled-function
     (limit)
     #<bytecode 0xdfbb89d7821003>)
    (0 'hi-pink prepend))
 (#f(compiled-function
     (limit)
     #<bytecode -0x16dd77d78192f2f9>)
    (0 'hi-yellow prepend)))
Local in buffer *scratch*; global value is nil

[back]
```

**Comment by jyp** [comment]
Are you using a compiled version of boon? I am wondering if using a .el directly could be a work around for the bug. If not, you could also try to call `hi-lock-set-pattern` directly and see if it updates hi-lock-interactive patterns correctly:

```
M-x eval-expression (hi-lock-set-pattern "abcd" (hi-lock-read-face-name))
```

**Comment by subsetpark** [comment]
I am using gccemacs, so I guess it's compiling boon. As for trying to eval that directly... I get an error in the minibuffer because it can't find the function. So that's quite odd.

```
Debugger entered--Lisp error: (void-function hi-lock-set-pattern)
  (hi-lock-set-pattern "stack" (hi-lock-read-face-name))
  eval-expression((hi-lock-set-pattern "stack" (hi-lock-read-face-name)) nil nil 127)
  funcall-interactively(eval-expression (hi-lock-set-pattern "stack" (hi-lock-read-face-name)) nil nil 127)
  command-execute(eval-expression record)
  counsel-M-x-action("eval-expression")
  ivy-call()
  ivy-read("M-x " [org-capture-goto-last-stored 0 flycheck-list-errors timer-next-integral-multiple-of-time otama hydra-message-timer term-do-line-wrapping ivy-explorer backquote-listify sgml-mode ivy-default-view-name c-electric-lt-gt pcomplete-stub newdir term-handle-exit &error flycheck-mode-line-prefix cl-struct-flycheck-syntax-check-tags 0 0 _save-matches edebug-mode-on-hook lisp-mode-map info--manual-names 0 viscii traversed compilation-error-list kmacro-pop-ring1 which-key--stop-timer nexus flycheck-pug-executable text-property--find-end-backward xref--push-markers 0 About 0 swiper-include-line-number-in-search adob--last-buffer kmacro-p use-package-handler/:interpreter magit-filename dired-do-chmod slot-unbound :match check-declare mmm-mode-on-maybe counsel--async-filter c-extra-toplevel-key flycheck-puppet-lint-disabled-arg-name ...] :predicate #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_33> :require-match t :history counsel-M-x-history :action counsel-M-x-action :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  command-execute(counsel-M-x)
```

**Comment by subsetpark** [comment]
This might be totally unrelated, but I *do* get this warning during the native compilation:

> Warning (comp): boon-moves.el:209:1: Warning: the function ‘boon-set-user-regexp’ is not known

**Comment by yantar92** [comment]
I observe the same issue. Also using gccemacas.

**Comment by aspiwack** [comment]
For the record, and the contrast, I use gccemacs as well, but have yet to encounter this issue.

**Comment by jyp** [comment]
Since the plot is thickening, I'll install gccemacs and get to the bottom of.

**Comment by jyp** [comment]
Ok, I know what the problem is now: hi-lock has been changed at some point. The gccemacs stuff just made it more difficult to do remote debugging. I'll have to do different code based on the version. So, to avoid breaking your setup @aspiwack , can you tell me what (emacs-version) says?

**Comment by aspiwack** [comment]
It says: "GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.21, cairo version 1.16.0)"

**Comment by jyp** [comment]
Tested on emacs 27.1 and 28.0.50.  Byte-compiled files not portable between versions. Re-open if it does not work on your system.

**Comment by subsetpark** [comment]
I can confirm it does resolve my issue!! Thank you so much @jyp for the indefatigable marathon debugging job.
