### ISSUE TITLE
Support for vterm-mode doesn't seem to work anymore

### ISSUE THREAD

**Issue by aspiwack** [jyp/boon#113]
In the past few weeks or so, I noticed that the special terminal support for vterm (introduced in #88 ) doesn't appear to work any more.

The initial mode is special, so `x` is captured (and attempting to go in command mode and `qx` gives a read-only buffer error).

I have no real idea when this changed. But it doesn't seem to affect other terminal modes (I've tried ansi-term, and it works fine).

Cc @tomterl

**Comment by jyp** [comment]
Unfortunately I can't reproduce the problem. My 'vterm' buffer is not special.

**Comment by aspiwack** [comment]
…

Thanks to your answer I figured out what was wrong. I had a customised `boon-special-mode-list` which was from way back and messed things up. I don't know why it just started to act up though. But it's solved. Thanks. And sorry for the noise :slightly_frowning_face:
