### ISSUE TITLE
Why do selectors return lambdas when `spec-selector' has special handling for them anyways?

### ISSUE THREAD

**Issue by hrehfeld** [jyp/boon#119]
In https://github.com/jyp/boon/blob/master/boon-arguments.el#L331 `(defun boon-spec-selector ...)`:

``` emacs-lisp
            (if (commandp kms)
          ;; we have a 'selector'. These commands may take prefix
          ;; args, which they input right away, and return a
          ;; continuation constructing the region depending on the
          ;; point/mark.
            (let ((current-prefix-arg my-prefix-arg))
              (call-interactively kms))
          ;; we have a 'move' command. Such commands do not take
          ;; non-universal arguments. So just run it in the
          ;; continuation.
            (lambda ()
              (save-excursion
                (let ((orig (point))
                      (current-prefix-arg my-prefix-arg)) ;; dynamic binding so env remains clean
                  (call-interactively kmv)
                  (list (boon-mk-reg orig (point) nil))))))
```

As we have special code for selectors anyways (they don't execute anything and just fake being commands (any technical reason that they are interactive at all?), why not change:

``` emacs-lisp
 (let ((current-prefix-arg my-prefix-arg))
              (call-interactively kms))
```

to automatically generate the lambda?

``` emacs-lisp
(lambda ()
 (let ((current-prefix-arg my-prefix-arg))
              (call-interactively kms)))
```

This would simplify the definition of all selector commands, they could just do their thing.

-------- 

Also, I have a few questions:

- is there an easy/canonical way to convert something like `expand-region` to boon selector commands? => this is probably `boon-select-from-region`
- why does `boon-spec-selector` have the special handling for the keymaps? Just because of `multiple-cursor` behavior?

**Comment by hrehfeld** [comment]
In boon-arguments.el `(defun boon-spec-selector ...)`:

``` emacs-lisp
            (if (commandp kms)
          ;; we have a 'selector'. These commands may take prefix
          ;; args, which they input right away, and return a
          ;; continuation constructing the region depending on the
          ;; point/mark.
            (let ((current-prefix-arg my-prefix-arg))
              (call-interactively kms))
          ;; we have a 'move' command. Such commands do not take
          ;; non-universal arguments. So just run it in the
          ;; continuation.
            (lambda ()
              (save-excursion
                (let ((orig (point))
                      (current-prefix-arg my-prefix-arg)) ;; dynamic binding so env remains clean
                  (call-interactively kmv)
                  (list (boon-mk-reg orig (point) nil))))))
```

As we have special code for selectors anyways (they don't execute anything and just fake being commands (any technical reason that they are interactive at all?), why not change:

``` emacs-lisp
 (let ((current-prefix-arg my-prefix-arg))
              (call-interactively kms))
```

to automatically generate the lambda?

``` emacs-lisp
(lambda ()
 (let ((current-prefix-arg my-prefix-arg))
              (call-interactively kms)))
```

This would simplify the definition of all selector commands.


-------- 

Also, I have a few questions:

- is there an easy/canonical way to convert something like `expand-region` to boon selector commands?
- why does `boon-spec-selector` have the special handling for the keymaps? Just because of `multiple-cursor` behavior?

**Comment by jyp** [comment]
The selectors are interactive, so that they can themselves read interactive arguments (and do so using the normal emacs mechanisms). Switching  lambda and call-interactively would mean that such arguments would be read for each cursor when multiple cursors are active. This is explained in the docstring of boon-spec-selector and in the comments.

For the other questions:
- `boon-select-from-region' seems like the way to go, yes. However `expand-region` fits very poorly with boon's design imo.
- The special handling is to support prefix arguments. There might be a better/simpler way based on installing a custom transient keymap? Not sure.
