### ISSUE TITLE
No focus on minibuffer

### ISSUE THREAD

**Issue by johanvts** [jyp/boon#12]
Thanks for writing boon-mode. I enjoy it a lot and have spend some time setting up my own QWERTY mode. I have found an annoying bug. It can be reproduced like this:

1. Run emacs in daemon mode
2. Open a file
3. Close emacs using "C-x C-c"
4. Change the file outside of emacs
5. Open the file again.

Emacs will show the "Revert buffer from file " minibuffer, but it will not be active.

**Comment by jyp** [comment]
Thanks for your kind words.

I could not reproduce the bug. I did:

0. touch blah
1. emacs --daemon
2. emacsclient blah
3.  C-x C-c
4. echo "abc" >> blah
5. emacsclient blah

Emacs did not show "Revert buffer from file".

**Comment by johanvts** [comment]
Sorry, I can't reproduce it today either. Must take something more to trigger the behavior. Thanks.
