### ISSUE TITLE
Deleted character is included in clipboard

### ISSUE THREAD

**Issue by skmd0** [jyp/boon#123]
### Description
The deleted character gets included into what text is copied. In my example it was `/` which I mistakenly typed it while in command mode.

### Expected result
The text that gets pasted should only include the line that was copied and not the deleted character.

### Video

https://user-images.githubusercontent.com/52122032/144252685-f56d2036-39d7-4369-b6a1-ca0019873e60.mp4

### Steps to reproduce

1. Write some text
2. Go to the start of the line
3. Insert `/` character while in command mode
4. Delete it by `d k`
5. Copy the whole line with `D SPC`
6. Go one line below `o`
7. Paste what you have in clipboard `f`

### Additional information

- GNU Emacs 27.2 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4) of 2021-08-07
- MELPA: boon - 20211125.2054
- Keyboard layout: qwerty

**Comment by jyp** [comment]
This is the normal behaviour of the kill ring in emacs.
