### ISSUE TITLE
VIMified layout - something for the wiki? Or maybe in Boon?

### ISSUE THREAD

**Issue by jacmoe** [jyp/boon#131]
I have been a [happy Boon user](https://github.com/jacmoe/.doom.d) for quite some time now, but I have been using a lot of window managers, file managers, even Neovim! lately, and found myself increasingly uncomfortable with the main movement keys whenever I find myself in Emacs.
So I modified the colemak layout slightly:

![keyboard-layout-colemak](https://user-images.githubusercontent.com/85424/221247562-c2c35809-1140-405b-afcb-ad47eac9e379.png)

```
   (boon-mode)

   (if (equal my-keyboard-variant "colemak")
       ;; we are using Colemak
       (progn
         (require 'boon-colemak)

         (define-key boon-moves-map "l" 'move-beginning-of-line)
         (define-key boon-moves-map "u" 'backward-sentence)
         (define-key boon-moves-map "U" 'ignore)
         (define-key boon-moves-map "y" 'forward-sentence)
         (define-key boon-moves-map "Y" 'ignore)
         (define-key boon-moves-map ";" 'move-end-of-line)

         (define-key boon-moves-map "H"  '("⇠" . boon-smarter-backward))        ;word
         (define-key boon-moves-map "h"  '("←" . backward-char))                ;character
         (define-key boon-moves-map "N"  'forward-paragraph)                    ;faster down
         (define-key boon-moves-map "n"  '("↓" . next-line))                    ;down
         (define-key boon-moves-map "e"  '("↑" . previous-line))                ;up
         (define-key boon-moves-map "E"  'backward-paragraph)                   ;faster up
         (define-key boon-moves-map "i"  '("→" . forward-char))                 ;character
         (define-key boon-moves-map "I"  '("→" . boon-smarter-forward))         ;word

         (define-key boon-moves-map "o"  '("hop" . avy-goto-word-1))
         (define-key boon-moves-map "O"  'avy-goto-char))

```

I have yet to do the qwerty layout, but the general idea is simple: HJKL instead of JKL;. "Hop" was moved.
Don't worry about the fact that I have modified the commands slightly to accomodate creative writing. The idea should be apparent.

I am sure that a lot of people trying out / evaluating Boon would appreciate the VIM-like navigation keys.

Together with the rest of Boon -> best of both worlds!

What do you think? Are you interested in at least put it in the wiki. As an example of modifying the layout to suit your needs.

EDIT: I will add the qwerty version in a comment when I get to it. I am already enjoying the modified colemak :) Makes a big difference in not having to remap muscle memory for the main movement keys when switching between Emacs and other (inferior :p ) programs.

**Comment by jyp** [comment]
Nice! I'm thinking that this should be a command (boon-vim-like-navigation), in its own file, say boon-vimlike.el and it can be referenced from the wiki. Would you care to write a PR?

**Comment by jacmoe** [comment]
As an alternative to boon-qwerty and boon-colemak?

Yes, I am willing to create a PR, when I have used the layout in both colemak and qwerty a bit.  :)

**Comment by jyp** [comment]
If I understand correctly you'd be better off with making it as an extra
layer on top of either. The simplest is probably to call (say) boon-colemak
and make the updates to the changed keymaps.

**Comment by jacmoe** [comment]
Yes, I was thinking that it could be `boon-colemak-vimlike` and `boon-qwerty-vimlike` to be required after `boon-colemak` or `boon-qwerty`.

Let's see what I come up with :)

**Comment by jacmoe** [comment]
I ended up with creating two layouts, `boon-qwerty-hjkl` and `boon-colemak-hnei`. People can then choose, for instance, between `boon-qwerty` or `boon-qwerty-hjkl`.
I think it's less open to errors that way :smile: 
I hope that it will increase adoption of Boon.
People have been bitching for years about the i3 window manager having "jkl;" as the movement commands out of the box. Now, at least here, with Boon, they don't even have to modify anything, except choosing a layout variant.

**Comment by jacmoe** [comment]
Thank you for accepting my PR, @jyp - excellent! :smile: :fireworks:
