### ISSUE TITLE
SPC SPC doesn't work on the last line of a buffer

### ISSUE THREAD

**Issue by aspiwack** [jyp/boon#16]
Selection of the current line with `SPC SPC` doesn't work on the last line of the buffer (it has an entertaining behaviour on the very first character of the last line though).

**Comment by jyp** [comment]
The `boon-select-line` selector uses `(bounds-of-thing-at-point 'visual-line)`. So, really, the bugs lies in there, and perhaps more precisely in `forward-visual-line`. So here are your options:

1. change or advise `forward-visual-line` to insert a newline when at the end of the buffer.
2. define a new function `always-forward-visual-line` doing the above, and change `boon-select-line` to use it
3. redefine the `SPC` selector in `boon-select-map` to your convenience

A potential issue with adding a newline when performing a selection is that emacs has a concept of narrowing. When a buffer is narrowed, the `always-forward-visual-line` will insert newlines at the end of the narrowed buffer, effectively in the middle of the complete buffer.

**Comment by aspiwack** [comment]
Let's close this.
