### ISSUE TITLE
Strange behavior on arrow keys with 'boon-drop-mark

### ISSUE THREAD

**Issue by johanvts** [jyp/boon#17]
When making a selection by pressing "SPC" in Command mode, some strange behavior appears:

Replicate:

1. Press "SPC". Minibuffer shows "mark 0"
2. Press any arrow key ex. "down", mini buffer displays "Wrong type argument: number-or-marker-p, down"

In my setup the down key is bound to " 'next-line". So is "k", however if I press "k" rather than down, the next line down is selected as expected. Also if I press "k" or any other non-arrow key bound to moving between lines or chars first, I can freely use the arrow keys to control the selection afterwards. There is only a problem if an arrow key is the first key pressed after "SPC". The problem is not present if I envoke 'set-mark-command

**Comment by jyp** [comment]
This issue should have been fixed by this commit: https://github.com/jyp/boon/commit/f381f0c00e98eee273d6337a528169eea3e06e7e

Can you check that you're using a version which includes this?

**Comment by johanvts** [comment]
I was using a package from 29th of September. But I updated now and the moves map contains those corrections, still the behavior persists.

**Comment by jyp** [comment]
What does M-x describe-key <down> say? 

Please also evaluate 
`(lookup-key boon-moves-map (kbd "<down>"))` and report the result.

**Comment by johanvts** [comment]
Describe key gives the same for arrows and rebound keys (ie. next-line) for both arrow down and "k".

Lookup-key returns next-line for down.
