### ISSUE TITLE
Deleting when replacing

### ISSUE THREAD

**Issue by johanvts** [jyp/boon#18]
Deletion appears broken when doing multicursor replace. How to replicate

1. In command mode "r @ w d" on a word.
2. Write some chars
3. Try to delete using Backspace (backward-delete-char-untabify)

Only the last occurrence of the word will have chars deleted, all other instances will be untouched by the deletion.

**Comment by jyp** [comment]
I can't reproduce this issue. Maybe your multiple cursors configuration
does something special with backspace? Could you try the command to another
key and check what happens then?

**Comment by johanvts** [comment]
Delete works as expected, <left> has similar behavior to backspace.

**Comment by jyp** [comment]
Please check the variables `mc/cmds-to-run-once` and `mc/cmds-to-run-for-all`. You probably have `backward-delete-char-untabify` in the wrong category.

**Comment by johanvts** [comment]
Right you are, thank you. Sorry to be pestering your issues list with all these things that are specific to my setup.

**Comment by jyp** [comment]
No worries. Besides this issue seems common enough (i've generalised the description).
