### ISSUE TITLE
Starting a buffer in insert mode

### ISSUE THREAD

**Issue by johanvts** [jyp/boon#19]
I want my LaTeX documents to start in insert mode rather than command mode, but adding 
> 'boon-set-insert-like-state
or
'boon-set-insert-state

to the hook does nothing. Documents are still opened in CMD mode.

**Comment by jyp** [comment]
As I understand it, this is because minor modes are activated after the hook is run. I can add a list of major modes to start in insert mode. Would that be fine by you?

**Comment by johanvts** [comment]
I though the problem would be that the hook is run too early, but didn't know how to fix it. Thanks
