### ISSUE TITLE
[suggestion] implement repeat last command using dot-mode minor mode

### ISSUE THREAD

**Issue by moesasji** [jyp/boon#21]
I've been looking at Boon as an alternative to Evil as the keybindings make a lot more sense on Colemak, but the big thing missing seems to be the "repeat last command" and in your todo.org you say you don't know how to implement it. 

Have you considered using the dot-mode minor mode to get this to work? See: https://github.com/wyrickre/dot-mode

Based on the description it looks like it should get most of the functionality that is needed (if not all).

**Comment by jyp** [comment]
Presumably you could load dot-mode and bind the 'repeat' command to whichever key you see fit. Did you try that?

**Comment by moesasji** [comment]
I have not used boon before, so this is a bit of a struggle. 

However installing boon and dot-mode in the way you suggest indeed allows me to repeat  simple edit commands such as "t o". Also a bit more advanced things such as "t 2 o" works to remove two words and then repeat the command by hitting "z". Deletions using avy-jumps however don't.

My first impression is that it seems a bit rudimentary in comparison to how the dot works in vim/evil. However that might simply be because I try things that work in Vim/Evil, which need to be done differently in boon. The most annoying aspect is that dot-mode has the "feature" of resetting when hitting the dot when the cursor is on a space, which is not what vim does.

Overall it doesn't seem to be a complete solution, but it might trigger some thoughts when playing with it.

**Comment by moesasji** [comment]
btw) Just in case you haven't seen it after you initially looked at ryo-modal. The following github repo came very close to implementing  vim-style editing by using ryo-modal, which does have the ability to repeat commands. 

https://github.com/sriramkswamy/ryo-emacs

It manages to do this using a single mode. A bit brute force, but it does get pretty close in how Evil works.

**Comment by jyp** [comment]
@moesasji The link that you provide is a complete configuration containing lots of non-relevant things. Do you know where the repeat command is implemented? Is it a feature of ryo-modal?

**Comment by moesasji** [comment]
Ryo-modal indeed has the repeat command implemented for any key bound using ryo-modal-key and it works well. It got implemented a couple of weeks after the author did the initial release of the package.

btw) the reason I linked to that noisy config is as an example that shows that despite using a single ryo-modal-mode state and "insert" mode one can get close to vim in functionality. So it might fit with what you aim for with Boon if repeat is important (which I think it is). Just food for thought.

**Comment by jyp** [comment]
Thanks. I'll take a look at ryo-modal when I get the chance.

**Comment by jyp** [comment]
In fact, ryo-modal does a very simple thing: it stores the last command run and allows to re-run it using a specific (other) command. That would *probably* work for boon too. Would you be satisfied with such a behaviour? (To be clear, an insertion won't be repeatable using this technique --- it could be extended though.)

**Comment by jyp** [comment]
I've added to master the possibility to repeat commands (bound to 'z'). Please let me know if you're satisfied or not.

**Comment by moesasji** [comment]
The repeat functionality added to master works nicely for basic commands and is a nice step forward. However I personally mostly use the dot-command in combination with a insert/edit operation. This misses that aspect, which make it far less useful. Essentially I think of hitting the dot as "repeat last change", which is why it is pretty easy to remember to use it for things like adding ";" to the end of lines as just one of the examples.

Adding that is probably not that easy, so feel free to close!

**Comment by jyp** [comment]
It's not easy, but I agree that it's pretty important. I leave the issue open in case people want to write ideas on how to do it neatly. Perhaps I can copy how evil does it.

**Comment by jyp** [comment]
I've implemented something for repeating inserts, can you try it and say if you're satisfied?

**Comment by jyp** [comment]
I'm closing, re-open if you're not satisfied with the solution.
