### ISSUE TITLE
smarter-backward not jumping correctly with counts

### ISSUE THREAD

**Issue by moesasji** [jyp/boon#22]
When using smarter-backward to jump defined number of words the behavior is not correct on the current master.

Testcase
One Two Three Four
Five  Six Seven Eight

Jumping words in the above with 2 followed by smarter-forward (C-u 2 o) jumps two words at a time as expected. For the equivalent 2 followed by smarter-backward jumps are however not correct. In the above testcase jumps are both one and 2 words in length, while all these jumps should be two words long.

In case it helps: error-message displayed: "Looking-back: Invalid search bound (wrong side of point)"

**Comment by jyp** [comment]
Fixed. Note that with the default keybindings you only need to type "2 n" to go back by 2 units (that's not exactly words, it'll skip over parens and in general try to be smart).
