### ISSUE TITLE
Make keymaps buffer local

### ISSUE THREAD

**Issue by yantar92** [jyp/boon#25]
Sometimes, I want to chenge the meaning of, say, `boon-smarter-downward` in specific buffers. For example, it makes more sense for me to use `org-next-visible-heading` binded to the same key as `boon-smarter-downward`.

Is it possible to set the keymap changes only for the current buffer?

**Comment by jyp** [comment]
You can always make a variable buffer local in your customization. There is no problem with that.

The best way to address the issue however would be to define a standard emacs command with the semantics to go to the next structural block. Boon would then simply use that, and it would ensure consistency throughout modes.

**Comment by yantar92** [comment]
> You can always make a variable buffer local in your customization. There is no problem with that.
 
I tried to do it. I am not sure if I am missing something, but the following still sets `boon-command-map` globally.

`  (add-hook 'after-init-hook (lambda ()
			       (make-variable-buffer-local 'boon-command-map)
			       (make-variable-buffer-local 'boon-special-map))))
   (add-hook 'ledger-mode-hook (lambda ()
  				(bind-keys :map boon-command-map
   					   ("J" . ledger-navigate-next-xact-or-directive)
  					   ("K" . ledger-navigate-prev-xact-or-directive))))
`

> The best way to address the issue however would be to define a standard emacs command with the semantics to go to the next structural block.

I do not fully understand. Do you mean that I can define the command, which will conditionally execute different commands depending on the major mode?

**Comment by jyp** [comment]
I suspect that bind-keys is doing an in-place update of the keymap. After make-variable-buffer-local, try to do something like 

```
(setq boon-command-map (copy-keymap boon-commande-map))
```

About my general comment: it's not a good idea if mode 'fight' to redefine keys. So you need cooperation between the modes, which needs to be mediated by an intermediate package (or standard emacs) which defines what a key should do in general. Simply speaking though, I don't feel comfortable making keymaps buffer-local as this will create surprises.

**Comment by yantar92** [comment]
> `(setq boon-command-map (copy-keymap boon-commande-map))`

I tried it:

```
  (add-hook 'ledger-mode-hook (lambda ()
  				(setq-local boon-command-map (copy-keymap boon-command-map))
  				(define-key boon-command-map "J" 'ledger-navigate-next-xact-or-directive)
  				(define-key boon-command-map "K" 'ledger-navigate-prev-xact-or-directive)
  				))
```

However, the key bindings remain to be mapped to `boon-smarter-downward` and `boon-smarter-upward` as it is the case globally. Completely weird.

In any case, I decided to give up on the local keymap idea (I agree that it redefining the keys may lead to unexpected behavior) and use your suggestion:

> The best way to address the issue however would be to define a standard emacs command with the semantics to go to the next structural block.

Now, I have something like below, using [meta-functions package](https://github.com/yantar92/meta-functions)

  (use-package meta-functions
    :config
    (meta-functions-add-meta-function '(meta-down-element boon-smarter-downward "Move down one element."))
    (meta-functions-add-meta-function '(meta-up-element boon-smarter-upward "Move up one element."))
    (meta-functions-add-meta-function '(meta-scroll-down scroll-down "Scroll down.")))

  (bind-keys 
	     :map boon-moves-map
	     ("J" . meta-down-element)
	     ("K" . meta-up-element))

  (use-package meta-functions
    :config
    (add-to-list 'meta-functions-meta-down-element-alist '(ledger-mode . ledger-navigate-next-xact-or-directive))
    (add-to-list 'meta-functions-meta-up-element-alist '(ledger-mode . ledger-navigate-prev-xact-or-directive))
    (meta-functions-update-function-definitions))

This closes the issue.
