### ISSUE TITLE
C-God does not reach C-c [::alpha::]

### ISSUE THREAD

**Issue by rschmidlin** [jyp/boon#27]
First I set <C-c f> with (global-set-key (kbd "C-c f") 'ggtags-find-file). 
If I press c followed by f in command mode, I get an error that C-c C-f is not bound. (No command bound to C-c C-f)
My examples:
C-c i -> No command bound to C-c TAB
C-c o -> No command bound to C-c C-o
C-c p -> No command bound to C-c C-p

I would like to understand the logic behind C-God. If I know correct, in the original God mode, c directly followed by i would mean C-c C-i whereas c followed by space and then by i would be C-c i.

**Comment by jyp** [comment]
You say that you bind "C-c f" and you get the message that "C-c C-f" is not bound. No inconsistency there.

You say that "ci" should give "C-c C-i"; that's what you get. (Similarly "cf" gives you "C-c C-f").

Now, "c<space>i" is not implemented. If you want this feature please create an issue for that.

**Comment by rschmidlin** [comment]
Thanks, after changing the bindings to prepend all letters with CTRL it worked. 

I thought the selection between prepending C or not was made automatically by boon-c-god because of its doc-string:
"Input a key sequence, prepend C- if that is a good choice, and run the command bound to that sequence."
If it only prepends C- if it is a good choice, I thought it would conversely leave it as is (no C-) if that was a good choice - my mistake.

**Comment by jyp** [comment]
Ok, I need to update the doc, and perhaps the behaviour to be more like god-mode. 

What is meant by the doc is that most special characters are never used in sequences of the form  C-c C-<special> and so if you use "c<special>" boon outputs "C-c <special>".
