### ISSUE TITLE
Use Insert mode for special buffers

### ISSUE THREAD

**Issue by jack038** [jyp/boon#28]
For me personally, having a special mode for special buffers like `dired` causes confusion. In `ansi-term` for example, I have to quote `x` or call `boon-insert` before typing. Is there a built in way to use Insert mode for special buffers? I am brand new to elisp, but I am willing to do the work if you could point me in the right direction.

Thanks!

**Comment by yantar92** [comment]
I am not aware about built in option like this. 
However, it is very easy to implement:

```
  (defvar boon-insert-state-major-mode-list '()
    "List of major modes started with insert state active.")
  (setq boon-insert-state-major-mode-list
	'(notmuch-message-mode eshell-mode calc-mode))
  (add-hook 'boon-local-mode-hook
	    (lambda() (when (and boon-local-mode
			    (member major-mode boon-insert-state-major-mode-list))
		   (boon-set-insert-state)))
	    'append)

```

**Comment by rschmidlin** [comment]
You can customize the variable boon-special-mode-list if you want other modes to use the special mode. For the other way around I did the following:

  ;; Define special modes where boon should be used instead
  (defvar boon-non-special-list
    '(bookmark-bmenu-mode))
  (defvar boon-new-special-list
    '())

  (defun use-special-mode-p (old-function &rest arguments)
    "Function to substitute boon-special-mode-p and disallow use of special mode for some major-modes"
    (or (memq major-mode boon-new-special-list)
        (and (apply old-function arguments)
             (not (memq major-mode boon-non-special-list)))))

  (advice-add #'boon-special-mode-p :around #'use-special-mode-p))

**Comment by jyp** [comment]
Another possibility is to unbind `x` (or whatever you may desire) in the special mode map.

**Comment by jack038** [comment]
I don't know which route I'll take, but both of those are good options. Thanks!
