### ISSUE TITLE
Example of using boon core ?

### ISSUE THREAD

**Issue by olymk2** [jyp/boon#31]
Looks like this may be the plugin I am after I wish to define my own modes and keys however.

Are there any existing examples of this the readme just talks about the boon keymap but it also mentions you could use boon-core to do your own.

What are the functions for defining a new mode and attaching key combinations to it perhaps something in the readme on this could be useful for others ? or have i completely mis understood and you cant define new modes and key combinations for the modes ?

**Comment by jyp** [comment]
Are you after defining a vi-style interface (command/insert states)? You could start by checking out boon-keys and boon-qwerty and define your own variants of bindings.

If you want to define a more states than "command/insert then you can use boon-core as a template but you'll need to add your own states.

**Comment by olymk2** [comment]
thanks for the quick reply yeah i want command/insert states but want the ability to add in new states beyond the basic ones, when you say use boon core does it have methods to add new modes or you mean create your own lisp to add in a mode based on boon core ?

**Comment by jyp** [comment]
At the moment boon does not offer the possibility to add new states with a simple command. You will need to change the code. It should not be too hard to add a macro to add a new state though, depending on your your elisp skills.

**Comment by olymk2** [comment]
Can you do mode specific shortcuts with boon, ie bind a specific short cut to org mode but have the same short cut do something different in python mode ?

**Comment by jyp** [comment]
There is no specific support for that, no. In theory you can make the keymaps buffer-local, but someone reported that it is not trivial to do so.

**Comment by yantar92** [comment]
Yes, I did not manage to make buffer-local keymaps work. However, I posted alternative solution in 
https://github.com/jyp/boon/issues/25.

**Comment by olymk2** [comment]
Thanks for the info been playing a bit with some lisp, thoughts on something like this ?

```
  (setq boon-key-list '
        ((org-mode . (message "%s" "command from org mode"))
         (lisp-mode . (message "%s" "command from lisp mode"))
         (python-mode . (message "%s" "command from python mode"))))

  (defun boon-detect-mode (boon-mode-map)
    (let
        ((boon-mode-command (cdr (assoc major-mode boon-mode-map))))
        (if boon-mode-command (apply boon-mode-command))))

  (defhydra hydra-home (global-map "<f2>" :exit t)
    "Main screen"
    ("t" (boon-detect-mode boon-key-list) "Test")
  )
```

Done some quick tests and seems to work but don't know enough to know if this method will cause issues further down the road ?

**Comment by yantar92** [comment]
I do not see why it would not work. The only thing is that documentation for the commands will be missing and you may need to dig your .emacs to figure out per-mode bindings.

**Comment by olymk2** [comment]
you mean because the docs would be for boon-detect-mode instead of the current modes command.

**Comment by yantar92** [comment]
Yes.

**Comment by olymk2** [comment]
```
  (setq boon-major-mode-hydra-list '
        ((org-mode . (hydra-org/body))
         (lisp-mode . (hydra-lisp/body))
         (js2-mode . (hydra-javascript/body))
         (javascript-mode . (hydra-javascript/body))
         (python-mode . (hydra-python/body))))

  (defun boon-select-major-mode (boon-mode-map)
    (let
        ((boon-mode-command (cdr (assoc major-mode boon-mode-map))))
        (if boon-mode-command (apply boon-mode-command))))

  (defun boon-mode-hydra ()
     (interactive)
     (boon-select-major-mode boon-major-mode-hydra-list))

  (define-key boon-command-map "," 'boon-mode-hydra)

  (defhydra hydra-javascript (:exit t :columns 4)
    "EM - Javascript"
    ("v" flycheck-verify-setup "Verify linting"))

```

Going to close this, thought i would post a complete working example showing how i have done it for others, basically just add you options to boon-major-mode-hydra-list and what it should call in my case i am using hydras for different modes binding to, so all major modes have a list of options under the same key.
