### ISSUE TITLE
Boon removing selection when switching mode

### ISSUE THREAD

**Issue by olymk2** [jyp/boon#33]
If I select a region then go into insert mode the region is unselected, is there an option to stop this from happening ? 

This is quite annoying if you use expand-region in command mode then want to enter insert mode for example.

**Comment by jyp** [comment]
Note that the mark remains. The region is merely 'deactivated'. Keeping the region active in command mode goes against the spirit of modal editing. However if you really need this I can make it configurable somehow.

**Comment by olymk2** [comment]
Will close this I cant remember the use case i had at the time, will update with more details if I hit the issue again
