### ISSUE TITLE
How to: add a key map under x in command mode

### ISSUE THREAD

**Issue by aspiwack** [jyp/boon#35]
I use projectile, which defines a keymap, I bound this keymap to `C-x p` like this:

```emacs-lisp
(use-package projectile
  :ensure t
  :bind-keymap
  ("C-x p" . projectile-command-map)
```

However, if I use `x p` in command mode, emacs complain that (from `*Messages*`):

> use-package-autoload-keymap: Key sequence x p starts with non-prefix key x

I'm not sure what I should do to make this work properly.

I'll transform the answer in this thread into a documentation PR.

**Comment by jyp** [comment]
You can do as follows:
```
  :bind (:map ctl-x-r-map ("p" . command))
```
in which case both `C-x` and `x` in command state will work, or 
```
  :bind (:map boon-x-map ("p" . command)))
```
for command state only.

**Comment by jyp** [comment]
No info; closing.
