### ISSUE TITLE
esc does not close minibuffers

### ISSUE THREAD

**Issue by leiserfg** [jyp/boon#36]
This is a minimal config for boon, I use a local mirror of melpa but it's up to date.
If I type `M-x` I can't go out by typing `esc`, and a warning is shown "Wrong type argument: commandp minibuffer-keyboard-quit" 
```elisp
       (require 'package)       
       (setq package-enable-at-startup nil)

       (add-to-list 'package-archives  '("melpa" . "~/elpa-mirror/melpa"))
       (add-to-list 'package-archives  '("org"   . "~/elpa-mirror/org/"))
       (add-to-list 'package-archives  '("gnu"   . "~/elpa-mirror/gnu/"))
       (package-initialize)
       
       (unless (package-installed-p 'use-package)
         (package-refresh-contents)
         (package-install 'use-package))
       (use-package boon
         :ensure t
         :init
         (require 'boon-qwerty)
         :config
         (boon-mode)
       )
```

**Comment by jyp** [comment]
I cannot manage to reproduce the bug. Here is my config:
```
(use-package boon
  :after dash expand-region
  :load-path "~/repo/boon"
  :diminish boon-local-mode
  :config
  (require 'boon-colemak)
  (boon-mode))
```

**Comment by tomterl** [comment]
I also have this problem (using `(require 'boon-qwerty)` as well, but I don't think thats the problem).

In my case, `minibuffer-keyboard-quit` is simply not a function, and it isn't defined in the boon-sources; I'm on emacs 26.1 -- is this a removed standard function, or provided by an uninstalled package?

**Comment by jyp** [comment]
I'm on emacs 26.1 and I can find `minibuffer-keyboard-quit` in delsel.el, like 293.
However --- this may not be the right function to call. Do you thik I should just use `keyboard-quit`, @tomterl ?

**Comment by tomterl** [comment]
Hmm - It seems like the function is not always loaded/active.  I checked the first time with `C-h f minibuffer-keyboard-quit RET` -- showing nothing.  Rechecking now yielded the expected result.  I don't know the correct action for this situation.  I normally don't use `delete-selection-mode`, maybe that's why? As far as I have read, I think `minibuffer-keyboard-quit` is correct.

**Comment by lattfein** [comment]
When I evaluate below with `emacs -Q`, `abort-recursive-edit` is assigned to `C-g`.
```
(add-to-list 'load-path "/path/to/boon")
(require 'boon-colemak)
(boon-mode)
```
So I think `abort-recursive-edit` should be assigned to `[escape]` or `(require 'delsel)`?
