### ISSUE TITLE
How to use my C-c *  shortcuts in CMD mode

### ISSUE THREAD

**Issue by leiserfg** [jyp/boon#39]
c is bound to boon-c-god but it doesn't work as god mode so c <space> x  maps to C-c C-SPC  x instead of C-c x

**Comment by jyp** [comment]
c x will do C-c C-x. If you want C-c x do c C-x.

**Comment by dimsuz** [comment]
> If you want C-c x do c C-x.

Hi! I suggest to mention this in the README or tutorial, this is not obvious.

I've searched for this clarification and thought that maybe there was an issue about this (and found it!), but it would be nice to have this clarified in docs somewhere.

Side question: is there something to quickly press "C-M" or "M" similar to how "x" does "C-x"? Coming from "meow-mode", where this is bound to "SPC g" and "SPC m" respectively. It seems there isn't something like this currently, not sure if there should be.
