### ISSUE TITLE
Block changing to CMD mode in special modes

### ISSUE THREAD

**Issue by emacsomancer** [jyp/boon#42]
So while modes in the Boon Special Mode List start in SPC mode, they still enter CMD mode on `ESC`, requiring `v`to return to SPC mode. (I'm using a CapsLck-as-both-Ctrl-and-ESC thing, so it's easy to accidentally turn on CMD mode in a SPC mode buffer.) Can't this just be blocked?

**Comment by aspiwack** [comment]
I use command mode in special buffers all the time (to move around, search, etc…). I would not like this :slightly_frowning_face:

**Comment by yantar92** [comment]
I would not like this kind of change as well, unless it is a user option.
For a time being, just remap you `ESC` to a custom function.
Say, 

````
(defun my/boon-set-command-state ()
  "Switch to command state."
  (interactive) 
  (unless (boon-special-mode-p)
  (boon-set-command-state)))
(define-key boon-special-map [escape] 'my/boon-set-command-state))
````
