### ISSUE TITLE
Special state not working in magit-blame-mode

### ISSUE THREAD

**Issue by zhaojiangbin** [jyp/boon#47]
To reproduce:

1. Enable boon everywhere with `boon-mode`.
2. Open a file tracked by git, then <kbd>M-x magit-blame</kbd>. I'd expect that mode line to show "SPC" at this point but its shows "CMD" instead. The keys from boon-command-map block the keys of the magit-blame keymaps.
3. In the same buffer, run <kbd>M-x boon-local-mode</kbd> twice to turn the mode off, then back on. Mode-line now shows "SPC" and the special map is active. Can use the magit-blame keys now. 
4. However, after the `magit-blame-mode` quits, the buffer stays in the special state instead of going back to the state before magit-blame started.

Running master at commit 0c25219ab9d51e4291933495909dde2c45ac3fb4.

**Comment by jyp** [comment]
Diagnosis:

Currently the choice between special/command mode is done only when toggling boon-mode (or when a new buffer is created). Magit-blame is a minor mode, and therefore no switch is done when activating/deactivating it.

Potential remedy: add a post-command hook to check for 'special' condition.

**Comment by zhaojiangbin** [comment]
Sorry for the late response. Advicing `magit-blame` works well. Thanks.
