### ISSUE TITLE
boon-qsearch-next-at-point `e s` jumps to part of words

### ISSUE THREAD

**Issue by duianto** [jyp/boon#56]
`e s` jumps to occurrences that are part of words.

```text
one
two
bone
two
```
With the cursor on the first line.
pressing: `e s`
highlights the first word `one`, but it also highlights and jumps to `one` in the word `bone`

boon-20181014.927
GNU Emacs 26.1 (build 1, x86_64-w64-mingw32) of 2018-05-30
Windows 10

**Comment by jyp** [comment]
Looks fixed in master. Reopen with more info if necessary.
