### ISSUE TITLE
Cheat sheet colors, hard to read black text on blue background

### ISSUE THREAD

**Issue by duianto** [jyp/boon#58]
Cheat sheet colors, hard to read black text on blue background

The cheat sheets that are linked in the https://github.com/jyp/boon#usage section:
https://github.com/jyp/boon/blob/master/colemak.pdf
https://github.com/jyp/boon/blob/master/qwerty.pdf

The blue color probably needs to be changed, because it's hard to read the black text on the 
blue (`#0000ff`) background color.

**Comment by jyp** [comment]
Fixed!
