### ISSUE TITLE
Document independent usage of `boon-core.el`/separate it out

### ISSUE THREAD

**Issue by transitracer** [jyp/boon#65]
It seems that you mention several times in the comparison that several packages (modalka and ryo-modal) are similar to `boon-core.el` but pale in comparison in several ways. As someone interested in generating their own modal editing mode based on their own editing habits who's looked at modalka and ryo-modal before and found them lacking and poorly integrated at times, this leaves me very interested in working with `boon-core.el`.

Are there any plans to document its usage (other than the existing code already using it) or, even better, separate it out and consider boon to be a modal editing package built on top of it?

**Comment by jyp** [comment]
There really isn't very much to it. Fill `boon-*-map` with the commands that you want. Call `boon-set-state` accordingly. If you have specific questions feel free to ask.
