### ISSUE TITLE
Boon command mode and chinese-py input method

### ISSUE THREAD

**Issue by yantar92** [jyp/boon#68]
When chinese-py is selecteed as input method, moving commands (i.e. "o") in boon command mode trigger inserting characters, which is not expected behavior. 

Steps to reproduce:
1. emacs -Q 
2. Load the following config: 
```
 (require 'package)
  (setq package-archives '(("MELPA" . "https://melpa.org/packages/") ("ELPA" . "http://tromey.com/elpa/") ("gnu" . "http://elpa.gnu.org/packages/") ("org" . "http://orgmode.org/elpa/"))
	load-prefer-newer t
	package-user-dir "~/.emacs.d/elpa/"
	package--init-file-ensured t
	package-enable-at-startup nil)
  (unless (file-directory-p package-user-dir)
    (make-directory package-user-dir t))
  (setq load-path (append '("~/.emacs.d/site-lisp/") load-path))
  (setq load-path (append (directory-files "~/.emacs.d/site-lisp/" t "^[^.]" t) load-path))
  (setq load-path (append (directory-files package-user-dir t "^[^.]" t) load-path))
  (add-hook 'after-init-hook #'package-initialize)
  (package-initialize 'NO-ACTIVATE)
(require 'use-package)
(use-package diminish :ensure t)
(require 'bind-key)

(use-package boon :ensure t
:config
(use-package boon-qwerty))

```
3. M-x turn-on-boon-mode
4. C-\ chinese-py <RET>
5. o ;; the chinese input is triggered instead of moving next line

**Comment by jyp** [comment]
I would say that this is a bug in emacs. Boon works by modifying `emulation-mode-map-alists` which should sensibly apply before input methods do their thing. However changing this behaviour may not be sensible given how keymap and input methods work, at all.

**Comment by yantar92** [comment]
Would it make sense to change input method to english when entering command state and restoring the input method in insert state?

**Comment by jyp** [comment]
Yes, that would definitely make sense. I'll see if I can implement that.

**Comment by contrapunctus-1** [comment]
Hi, thanks for this package This issue is my chief complaint with modal packages for Emacs (e.g. god-mode). With Boon, I tested the following -
1. Boon insert mode ( v )
2. Change IM to Devanagari iTrans ( C-\ )
3. Boon command mode ( ESC ). The "DevITU" indicator goes away.
4. Type a Boon command, e.g. o . The respective Devanagari IM character is typed instead of the command being executed.

**Comment by jyp** [comment]
@contrapunctus-1  I am now using this feature all the time, in the way you described, with no problem.
In my init.el, I have:
```
(setq default-input-method "Agda")
```
Which version of emacs/boon are you using?

**Comment by contrapunctus-1** [comment]
GNU Emacs 26.1 (build 2, i686-pc-linux-gnu, GTK+ Version 3.24.5) of 2019-09-23, modified by Debian

Boon version: 20191001.1211

**Comment by jyp** [comment]
That's extremely surprising, especially since you're seeing the modeline showing the expected input method. Can you check the value of "current-input-method" when you're back in command mode?

**Comment by contrapunctus-1** [comment]
It's `nil`, both buffer-locally and globally.

**Comment by jyp** [comment]
@contrapunctus-1 Can you check the latest commit?

**Comment by contrapunctus-1** [comment]
Awesome, it's fixed! Thanks! :smiley:

**Comment by jyp** [comment]
Thanks for the report!
