### ISSUE TITLE
Customizing the cursor face in insert mode

### ISSUE THREAD

**Issue by XL3** [jyp/boon#71]
Is there a possibility for the cursor face of insert mode to be different from the one of command mode?

**Comment by jyp** [comment]
I am not aware of such at thing as a cursor face. However you can readily customize `boon-insert-cursor-type` and `boon-command-cursor-type`.

**Comment by jyp** [comment]
I saw that I was mistaken and there is in fact a `cursor` face.  According to the doc only the background color is meaningful, and it seems more meaningful to call `set-cursor-color` with a customizable argument when the state changes. (Besides, I see that `set-cursor-color` changes the cursor color in all windows and buffers.) Would this behavior suit your needs?

**Comment by onecalled3bkr** [comment]
I was looking for something buffer-specific, but I haven't had any luck.

**Comment by jyp** [comment]
Too bad, let's leave this open for now. FWIW RYO modal calls `set-cursor-color` for this purpose.
