### ISSUE TITLE
Emacs-like frontend

### ISSUE THREAD

**Issue by contrapunctus-1** [jyp/boon#78]
Boon eschews Emacs keybinding conventions in favor of ergonomics. While I personally like trying new approaches, I reckon not all users are that keen - and yet, outside of ergonomics, Boon has other useful ideas like modal editing, text objects, and control over whitespace.

As a solution, I'm working on a keybinding frontend PR for the Qwerty layout which takes the opposite route (e.g. next-line and previous-line are n and p), where a user with default/close-to-default Emacs keybindings will feel right at home and will not experience inconsistency with other Emacs components like info, ibuffer, magit, proced, dired, package-menu etc.

Please let me know if it's appropriate to include it in Boon itself, and any feedback/ideas for such a frontend.

**Comment by jyp** [comment]
I'll merge this into boon --- it seems to me natural place to have this. But note that it should be a separate frontend file (`boon-emacs-idiomatic.el`).

**Comment by berndjr** [comment]
I agree with the goal of having Emacs idiomatic keybindings and am working on such a frontend [boon-emacs.txt](https://github.com/jyp/boon/files/3982128/boon-emacs.txt). I also remapped two bindings from `boon-keys.el`, the keys for `undo` and and `boon-drop-mark`.

**Comment by jyp** [comment]
@berndjr Do I have your permission to include this in boon ? Do you prefer to do a PR?

**Comment by berndjr** [comment]
It is ok to include my fontend into boon, but I would prefer to match it with the work of @contrapunctus-1 first, if possible. And I am not sure if it is good to remap key bindings from `boon-keys.el` or it is better to remove this. My frontend is still a bit in progress; I will make a pull request in a couple of days.
@contrapunctus-1: Can you share your solution?

**Comment by contrapunctus-1** [comment]
Unfortunately my laptop has been quite busted since I last wrote. I'll try sharing it from a backup as soon as I can.

**Comment by berndjr** [comment]
I have created a pull request with a revised version of `boon-emacs.el`. I have eliminiated the remappings of bindings from `boon-keys.el`.

**Comment by jyp** [comment]
Seems like I missed this due to being overworked. Could you re-open the PR?

**Comment by bernardjosef** [comment]
I have made a new version of boon-emacs.el on a separate branch. I will make a new PR for this.

**Comment by jyp** [comment]
This was merged some time ago. Closing.
