### ISSUE TITLE
; and ç to move forward a word

### ISSUE THREAD

**Issue by OrionRandD** [jyp/boon#81]
Hi,
I use two keyboard: us-intl and portuguese-abnt2.
How do I map "ç" to, which is in the place of ";" - in the abnt2 - also move forward a word?
Thx a lot

**Comment by OrionRandD** [comment]
I already found out how.
It works here. I do not know if this is the right way though.
I have put it in my init.el
(define-key boon-moves-map "ç" 'boon-smarter-forward)

**Comment by jyp** [comment]
This is, in fact, the best way to go about it!
