### ISSUE TITLE
Switch to special state in View mode

### ISSUE THREAD

**Issue by bernardjosef** [jyp/boon#83]
In View mode the buffer should be set to special state instead of command state. This is not easy to achieve, because View mode is a minor mode. In my personal settings I have the following:

    (defun my-boon-view-mode-special-state ()
        "In View mode, switch to special state."
        (and boon-local-mode
             (or boon-insert-state
                 (boon-special-mode-p)
                 (boon-set-state (if (null view-mode) 'boon-command-state
                                   (setq cursor-type (default-value 'cursor-type))
                                   'boon-special-state)))))
    (add-hook 'view-mode-hook #'my-boon-view-mode-special-state)
    (defun my-boon-view-mode-quote-character (char)
      "In View mode, recognize `view-mode-map'."
       (interactive (list (read-char)))
       (let ((cmd (and (bound-and-true-p view-mode) (lookup-key view-mode-map (vector char)))))
        (if (null cmd)
             (boon-quote-character char)
        (setq last-command-event char)
        (message "Executing the command bound to %c" char)
        (call-interactively cmd nil [char]))))
    (define-key boon-special-map [remap boon-quote-character] #'my-boon-view-mode-quote-character))

Maybe this can be incorporated into boon somehow.

**Comment by jyp** [comment]
You can customize `boon-special-conditions` and/or submit a PR adding `(bound-and-true-p view mode)` there.

**Comment by berndjr** [comment]
That does not work, unfortunately, because View mode is a minor mode and is set after `boon-special-mode-p` is called. And if `view-mode` is called inside a buffer, `boon-special-mode-p` is not called at all. The other problem is that `boon-quote-character` does not recognize minor mode maps. I added the `view-mode-map` in `my-boon-view-mode-character` explicitlt, but maybe this should be customizable, so that other minor modes can be added.

**Comment by jyp** [comment]
I've added the view-mode condition to special state and fixed boon-quote-character. If you also want to switch to special state when activating view mode, you can add boon-set-insert-like-state to view-mode-hook
